### ISSUE TITLE
v.1.3.0 Stage - caliper-simple-json errors

### ISSUE THREAD

**Issue by jarusified** [LLNL/CallFlow#96]
The stage branch fails to load the `supergraph` view for the single-rank case (e.g., caliper-simple-json). The following are the error logs associated failed endpoint fetches. 

-- boxplot 
```
2021-07-26 11:19:57,439 - server.provider_api:log_exception:1892 - ERROR - Exception on /single_boxplots [POST]
Traceback (most recent call last):
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jarus/miniconda/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jarus/miniconda/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/jarus/Work/llnl/CallFlow/server/provider_api.py", line 217, in single_boxplot
    result = self.request_single({"name": "boxplots", **data})
  File "/Users/jarus/Work/llnl/CallFlow/server/provider_base.py", line 493, in request_single
    sg=sg, name=callsite, ntype=ntype, proxy_columns=sg.proxy_columns
  File "/Users/jarus/Work/llnl/CallFlow/callflow/modules/boxplot.py", line 88, in __init__
    self.result["tgt"] = self.compute(df)
  File "/Users/jarus/Work/llnl/CallFlow/callflow/modules/boxplot.py", line 101, in compute
    mask = outliers(df[tv], scale=self.iqr_scale)
  File "/Users/jarus/Work/llnl/CallFlow/callflow/utils/utils.py", line 134, in outliers
    assert isinstance(data, (pd.Series, np.ndarray))
AssertionError
```

-- single_histogram and single_scatterplot.
```
07-26 11:19:57,429 - server.provider_api:log_exception:1892 - ERROR - Exception on /single_scatterplot [POST]
Traceback (most recent call last):
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jarus/miniconda/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jarus/miniconda/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/jarus/Work/llnl/CallFlow/server/provider_api.py", line 210, in single_scatterplot
    result = self.request_single({"name": "scatterplot", **data})
  File "/Users/jarus/Work/llnl/CallFlow/server/provider_base.py", line 424, in request_single
    for module_idx in sg.module_aux_dict.keys()
  File "/Users/jarus/Work/llnl/CallFlow/server/provider_base.py", line 424, in <dictcomp>
    for module_idx in sg.module_aux_dict.keys()
  File "/Users/jarus/Work/llnl/CallFlow/callflow/datastructures/supergraph.py", line 115, in get_name
    return self.idx2module[idx]
KeyError: (17, 17)
```

**Comment by jarusified** [comment]
Closing the issue since it was fixed in v.1.3.0
