### ISSUE TITLE
v.1.3.0 Stage - Caliper .cali file missing column - "time"

### ISSUE THREAD

**Issue by jarusified** [LLNL/CallFlow#97]
The sample datasets `caliper-simple-cali` and `caliper-lulesh-cali` fail to load the VIS because of the missing "time" column. 

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/jarus/miniconda/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/jarus/miniconda/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/jarus/Work/llnl/CallFlow/server/provider_base.py", line 133, in mp_dataset_load
    read_parameter=read_param,
  File "/Users/jarus/Work/llnl/CallFlow/callflow/datastructures/supergraph.py", line 443, in load
    apply_func=lambda _: _.mean(),
  File "/Users/jarus/Work/llnl/CallFlow/callflow/utils/df.py", line 124, in df_bi_level_group
    return {_: _df.xs(_)[_cols] for _ in _levels}
  File "/Users/jarus/Work/llnl/CallFlow/callflow/utils/df.py", line 124, in <dictcomp>
    return {_: _df.xs(_)[_cols] for _ in _levels}
  File "/Users/jarus/miniconda/lib/python3.7/site-packages/pandas/core/series.py", line 906, in __getitem__
    return self._get_with(key)
  File "/Users/jarus/miniconda/lib/python3.7/site-packages/pandas/core/series.py", line 946, in _get_with
    return self.loc[key]
  File "/Users/jarus/miniconda/lib/python3.7/site-packages/pandas/core/indexing.py", line 879, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/Users/jarus/miniconda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1099, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/Users/jarus/miniconda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1037, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/Users/jarus/miniconda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1254, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/Users/jarus/miniconda/lib/python3.7/site-packages/pandas/core/indexing.py", line 1316, in _validate_read_indexer
    "Passing list-likes to .loc or [] with any missing labels "
KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['time'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "venv/bin/callflow", line 33, in <module>
    sys.exit(load_entry_point('CallFlow', 'console_scripts', 'callflow')())
  File "/Users/jarus/Work/llnl/CallFlow/server/main.py", line 81, in main
    cf.load()
  File "/Users/jarus/Work/llnl/CallFlow/server/provider_base.py", line 103, in load
    partial(self.mp_dataset_load, save_path=load_path), self.datasets
  File "/Users/jarus/miniconda/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/jarus/miniconda/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['time'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"
```

**Comment by jarusified** [comment]
Closing the issue since it was fixed in v.1.3.0
