### ISSUE TITLE
v.1.3.0 Stage - hpctoolkit-allgather-database fails to load some VIS due to timeout

### ISSUE THREAD

**Issue by jarusified** [LLNL/CallFlow#98]
-- SuperGraph
Issue: The endpoint request timesout because of some cycle issue I believe.

-- CCT 
Issue: callsite index mapping is not matching certain callsites. Could be a bug.
```
2021-07-26 11:28:23,139 - server.provider_api:log_exception:1892 - ERROR - Exception on /cct [POST]
Traceback (most recent call last):
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jarus/miniconda/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jarus/Work/llnl/CallFlow/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jarus/miniconda/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/jarus/Work/llnl/CallFlow/server/provider_api.py", line 146, in single_cct
    nxg = self.request_general({"name": "cct", **data})
  File "/Users/jarus/Work/llnl/CallFlow/server/provider_base.py", line 389, in request_general
    nll = NodeLinkLayout(sg=sg, selected_runs=operation["dataset"])
  File "/Users/jarus/Work/llnl/CallFlow/callflow/layout/node_link.py", line 48, in __init__
    self._add_node_attributes()
  File "/Users/jarus/Work/llnl/CallFlow/callflow/layout/node_link.py", line 78, in _add_node_attributes
    datamap[column][callsite] = self.sg.get_module(callsite_idx)
  File "/Users/jarus/Work/llnl/CallFlow/callflow/datastructures/supergraph.py", line 140, in get_module
    return self.callsite2module[callsite_idx]
KeyError: 107
```

**Comment by jarusified** [comment]
Closing the issue since it was fixed in the v.1.3.0 release.
